//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiWM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.РезервыТоваров = new HashSet<РезервыТоваров>();
            this.ЭлементыЗаказа = new HashSet<ЭлементыЗаказа>();
        }
    
        public int IDЗаказа { get; set; }
        public string ТипЗаказа { get; set; }
        public System.DateTime ДатаЗаказа { get; set; }
        public Nullable<int> IDПоставщика { get; set; }
        public Nullable<int> IDКлиента { get; set; }
        public string СтатусЗаказа { get; set; }
        public decimal ОбщаяСумма { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Поставщики Поставщики { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РезервыТоваров> РезервыТоваров { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭлементыЗаказа> ЭлементыЗаказа { get; set; }
    }
}
