//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiWM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Инвентаризация
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Инвентаризация()
        {
            this.ЭлементыИнвентаризации = new HashSet<ЭлементыИнвентаризации>();
        }
    
        public int IDИнвентаризации { get; set; }
        public System.DateTime ДатаИнвентаризации { get; set; }
        public string ОтветственноеЛицо { get; set; }
        public string Результаты { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭлементыИнвентаризации> ЭлементыИнвентаризации { get; set; }
    }
}
