//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiWM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПриходныеНакладные
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ПриходныеНакладные()
        {
            this.ЭлементыПриходнойНакладной = new HashSet<ЭлементыПриходнойНакладной>();
        }
    
        public int IDНакладной { get; set; }
        public string НомерНакладной { get; set; }
        public System.DateTime ДатаПоступления { get; set; }
        public int IDПоставщика { get; set; }
        public decimal ОбщаяСумма { get; set; }
    
        public virtual Поставщики Поставщики { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭлементыПриходнойНакладной> ЭлементыПриходнойНакладной { get; set; }
    }
}
