//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiWM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class РасходныеНакладные
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public РасходныеНакладные()
        {
            this.ЭлементыРасходнойНакладной = new HashSet<ЭлементыРасходнойНакладной>();
        }
    
        public int IDНакладной { get; set; }
        public string НомерНакладной { get; set; }
        public System.DateTime ДатаОтгрузки { get; set; }
        public int IDКлиента { get; set; }
        public decimal ОбщаяСумма { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭлементыРасходнойНакладной> ЭлементыРасходнойНакладной { get; set; }
    }
}
