//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiWM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Склады
    {
        public int IDСклада { get; set; }
        public string Название { get; set; }
        public string Адрес { get; set; }
        public string ТипСклада { get; set; }
        public string ЗонаХранения { get; set; }
        public Nullable<int> IDТовара { get; set; }
        public Nullable<int> Количество { get; set; }
    }
}
