//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiWM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.РезервыТоваров = new HashSet<РезервыТоваров>();
            this.ЭлементыЗаказа = new HashSet<ЭлементыЗаказа>();
            this.ЭлементыИнвентаризации = new HashSet<ЭлементыИнвентаризации>();
            this.ЭлементыПриходнойНакладной = new HashSet<ЭлементыПриходнойНакладной>();
            this.ЭлементыРасходнойНакладной = new HashSet<ЭлементыРасходнойНакладной>();
        }
    
        public int IDТовара { get; set; }
        public string Название { get; set; }
        public string Артикул { get; set; }
        public string Штрихкод { get; set; }
        public string Категория { get; set; }
        public string ЕдиницаИзмерения { get; set; }
        public decimal Цена { get; set; }
        public string СерийныйНомер { get; set; }
        public Nullable<int> МинимальныйЗапас { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РезервыТоваров> РезервыТоваров { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭлементыЗаказа> ЭлементыЗаказа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭлементыИнвентаризации> ЭлементыИнвентаризации { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭлементыПриходнойНакладной> ЭлементыПриходнойНакладной { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭлементыРасходнойНакладной> ЭлементыРасходнойНакладной { get; set; }
    }
}
